[tool.black]
line_length = 80

[tool.isort]
profile = "black"
line_length = 80
virtual_env = "env"

[tool.pylint."messages control"]
disable = ["C0330", "C0326"]

[tool.pylint.format]
max-line-length = "80"

[tool.mypy]
strict = true
exclude = ".*tests.*"

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = [
    "tests",
]
